name: Changelog compilation

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  changelogs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout website
      uses: actions/checkout@v3
      with:
        path: fluvio-website
      
    - name: pulling fluvio-connectors
      uses: actions/checkout@v3
      with:
        repository: infinyon/fluvio-connectors
        ref: main
        path: fluvio-connectors
        
    - name: move old data out and replace
      run: |
        pwd
        find . ! -name CHANGELOG.md -type f -delete
        find . -type d -empty -delete
        cd ..
        cp -r fluvio-connectors/rust-connectors fluvio-website/changelogs/base/connectors/rust-connectors
        cd fluvio-website

    - name: Compile Configs
      run: python3 ./scripts/changelog.py


    - name: commit & push update
      uses: github-actions-x/commit@v2.9
      with:
        # Github Token with commit access
        github-token: ${{ secrets.GITHUB_TOKEN}}
        # Specify commit message
        commit-message: Commiting modification to Changelogs!
        # Force add files, useful for adding ignored files.
        force-add: true
        # Force push.
        force-push: false # optional, default is false
        # Pull and rebase before commiting. Useful when using commit inside matrix.
        rebase: false # optional, default is false
        # Specific files to add.
        files: ./changelogs/compiled/*
        # Committer name. Default is name of the person or app that initiated the workflow.
        name: changelog Bot
