name: Changelog compilation

on:
  push:
  
  pull_request:
    branches: [master]
  workflow_dispatch:
jobs:
  changelogs:
    name: Compile Changelogs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: compile changelogs
        run: ./scripts/changelog.py
